# Generated by Django 4.1.7 on 2023-03-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_city_profile_state_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(blank=True, default='Individual', max_length=255, null=True),
        ),
    ]
